package com.xworkz.namma_metro.constants;

public enum SortTickets {
    TICKETIDASC,TICKETIDDESC,FROMASC,FROMDESC,TOASC,TODESC,
    NOOFTICKETSASC,NOOFTICKETSDESC,PAYMENTOPTIONASC,PAYMENTOPTIONDESC,
    AMOUNTASC,AMOUNTDESC,USERIDASC,USERIDDESC;
}
