package com.xworkz.namma_metro.constants;

public enum SortUsers {
    USERIDASC,USERIDDESC,NAMEASC,NAMEDESC,EMAILASC,EMAILDESC,
    CONTACTNOASC,CONTACTNODESC,GENDERASC,GENDERDESC,ADDRESSASC,ADDRESSDESC;
}
